# Generated by expdpy ExPdPy — reproducible analysis script

# --- Setup ---
import pandas as pd
import expdpy as ex

# --- Load the analysis sample ---
df = pd.read_parquet('expdpy_sample.parquet')
data_def = pd.read_csv('expdpy_data_def.csv')
df = ex.set_labels(df, data_def, set_panel=True)
df.head()

# --- Bar chart ---
ex.explore_bar_plot(df, var='None').fig

# --- Missing values ---
ex.explore_missing_values_plot(df, time='year').fig

# --- Descriptive statistics ---
res = ex.explore_descriptive_table(df.select_dtypes('number'))
res.gt

# --- Histogram ---
ex.explore_histogram(df, var='None', bins=20).fig

# --- Extreme observations ---
ex.explore_ext_obs_table(df, n=5, var='None').gt

# --- By-group bar graph ---
ex.explore_bar_plot_by_group(df, by_var='None', var='None').fig

# --- By-group violin graph ---
ex.explore_violin_plot_by_group(df, by_var='None', var='None').fig

# --- Trend graph ---
ex.explore_trend_plot(df, var=[], time='year').fig

# --- Quantile trend graph ---
ex.explore_quantile_trend_plot(df, var='None', quantiles=[0.05, 0.25, 0.5, 0.75, 0.95], time='year').fig

# --- By-group trend graph ---
ex.explore_trend_plot_by_group(df, group_var='None', var='None', time='year').fig

# --- Correlations ---
ex.explore_correlation_plot(df.select_dtypes('number')).fig

# --- Scatter plot ---
ex.explore_scatter_plot(df, x='None', y='None', color=None, size=None, loess=1).fig

# --- Regression ---
res = ex.analyze_regression_table(df, dvs='None', idvs=[], feffects=[], clusters=[])
res.etable
